import type { CollectionConfig } from 'payload'

export const ListeningCommittee: CollectionConfig = {
  slug: 'listening-committee',
  labels: { singular: 'Listener', plural: 'Listeners' },
  admin: {
    useAsTitle: 'email',
    defaultColumns: [
      'firstName',
      'lastName',
      'email',
      'genreFirst',
      'isReturning',
      'status',
      'createdAt',
    ],
    group: 'Festival',
  },
  access: {
    read: ({ req }) => Boolean(req.user),
    create: () => true,
    update: ({ req }) => Boolean(req.user),
    delete: ({ req }) => Boolean(req.user),
  },
  fields: [
    {
      type: 'row',
      fields: [
        { name: 'firstName', type: 'text', label: 'First Name', required: true },
        { name: 'lastName', type: 'text', label: 'Last Name', required: true },
      ],
    },
    { name: 'email', type: 'email', label: 'Email', required: true },
    { name: 'phone', type: 'text', label: 'Phone Number', required: true },
    {
      name: 'betterAuthId',
      type: 'text',
      label: 'Better Auth User ID',
      admin: { readOnly: true, description: 'Set automatically on signup' },
    },
    {
      name: 'genreFirst',
      type: 'select',
      label: 'First Choice Genre',
      required: true,
      options: [
        { label: 'Classical', value: 'classical' },
        { label: 'Country', value: 'country' },
        { label: 'Electronic', value: 'electronic' },
        { label: 'Experimental', value: 'experimental' },
        { label: 'Folk / Americana', value: 'folk_americana' },
        { label: 'Hip Hop / Rap', value: 'hip_hop' },
        { label: 'International', value: 'international' },
        { label: 'R&B / Soul', value: 'rb_soul' },
        { label: 'Jazz', value: 'jazz' },
        { label: 'Metal / Hardcore', value: 'metal_hardcore' },
        { label: 'Pop', value: 'pop' },
        { label: 'Post-Punk', value: 'post_punk' },
        { label: 'Rock / Alt / Punk', value: 'rock_alt_punk' },
        { label: 'Indie Rock / Pop', value: 'indie_rock_pop' },
        { label: 'Goth / Dark-Wave', value: 'goth_darkwave' },
      ],
    },
    {
      name: 'genreSecond',
      type: 'select',
      label: 'Second Choice Genre',
      options: [
        { label: 'Classical', value: 'classical' },
        { label: 'Country', value: 'country' },
        { label: 'Electronic', value: 'electronic' },
        { label: 'Experimental', value: 'experimental' },
        { label: 'Folk / Americana', value: 'folk_americana' },
        { label: 'Hip Hop / Rap', value: 'hip_hop' },
        { label: 'International', value: 'international' },
        { label: 'R&B / Soul', value: 'rb_soul' },
        { label: 'Jazz', value: 'jazz' },
        { label: 'Metal / Hardcore', value: 'metal_hardcore' },
        { label: 'Pop', value: 'pop' },
        { label: 'Post-Punk', value: 'post_punk' },
        { label: 'Rock / Alt / Punk', value: 'rock_alt_punk' },
        { label: 'Indie Rock / Pop', value: 'indie_rock_pop' },
        { label: 'Goth / Dark-Wave', value: 'goth_darkwave' },
      ],
    },
    {
      name: 'isReturning',
      type: 'select',
      label: 'Previous Committee Member',
      required: true,
      options: [
        { label: 'Yes!', value: 'yes' },
        { label: 'No, this is my first time!', value: 'no' },
      ],
    },
    {
      name: 'mailingList',
      type: 'checkbox',
      label: 'Include on mailing list',
      defaultValue: false,
    },
    {
      name: 'status',
      type: 'select',
      label: 'Status',
      defaultValue: 'active',
      options: [
        { label: 'Active', value: 'active' },
        { label: 'Inactive', value: 'inactive' },
      ],
    },
    {
      name: 'assignedBatch',
      type: 'text',
      label: 'Assigned Batch',
      admin: {
        description: 'Set by director when listening process begins',
        readOnly: false,
      },
    },
  ],
  timestamps: true,
}
