import type { CollectionConfig } from 'payload'

export const CompilationSubmissions: CollectionConfig = {
  slug: 'compilation-submissions',
  labels: { singular: 'Submission Data', plural: 'Submission Data' },
  admin: {
    useAsTitle: 'artistName',
    defaultColumns: [
      'createdAt',
      'artistName',
      'songTitle',
      'genre',
      'releaseStatus',
      'radioAppropriate',
      'status',
    ],
    group: 'Compilation',
  },
  access: {
    read: ({ req }) => Boolean(req.user),
    create: () => true,
    update: ({ req }) => Boolean(req.user),
    delete: ({ req }) => Boolean(req.user),
  },
  fields: [
    {
      name: 'id',
      type: 'text',
      defaultValue: () => crypto.randomUUID(),
      admin: { readOnly: true, hidden: true },
    },
    { name: 'artistName', type: 'text', label: 'Artist Name', required: true },
    { name: 'songTitle', type: 'text', label: 'Song Title', required: true },
    {
      name: 'genre',
      type: 'select',
      label: 'Primary Genre',
      required: true,
      options: [
        { label: 'Classical', value: 'classical' },
        { label: 'Country', value: 'country' },
        { label: 'Electronic', value: 'electronic' },
        { label: 'Experimental', value: 'experimental' },
        { label: 'Folk / Americana', value: 'folk_americana' },
        { label: 'Hip Hop / Rap', value: 'hip_hop' },
        { label: 'International', value: 'international' },
        { label: 'R&B / Soul', value: 'rb_soul' },
        { label: 'Jazz', value: 'jazz' },
        { label: 'Metal / Hardcore', value: 'metal_hardcore' },
        { label: 'Pop', value: 'pop' },
        { label: 'Post-Punk', value: 'post_punk' },
        { label: 'Rock / Alt / Punk', value: 'rock_alt_punk' },
        { label: 'Indie Rock / Pop', value: 'indie_rock_pop' },
        { label: 'Goth / Dark-Wave', value: 'goth_darkwave' },
      ],
    },
    {
      name: 'releaseStatus',
      type: 'select',
      label: 'Release Status',
      required: true,
      options: [
        { label: 'Unreleased Track', value: 'unreleased' },
        { label: 'Self-Released Track', value: 'self_released' },
        { label: 'Released on Label', value: 'on_label' },
        { label: 'Already hosted on Soundcloud', value: 'soundcloud' },
      ],
    },
    { name: 'labelName', type: 'text', label: 'Label Name' },
    {
      name: 'radioAppropriate',
      type: 'select',
      label: 'Radio Appropriate',
      required: true,
      options: [
        { label: 'Radio Friendly', value: 'radio_friendly' },
        { label: 'Parental Advisory', value: 'parental_advisory' },
      ],
    },
    {
      name: 'songwritingCreditMusic',
      type: 'array',
      label: 'Songwriting Credit — Music',
      fields: [
        { name: 'name', type: 'text', label: 'Name' },
        { name: 'split', type: 'number', label: 'Split %', min: 0, max: 100 },
      ],
    },
    {
      name: 'songwritingCreditLyrics',
      type: 'array',
      label: 'Songwriting Credit — Lyrics',
      fields: [
        { name: 'name', type: 'text', label: 'Name' },
        { name: 'split', type: 'number', label: 'Split %', min: 0, max: 100 },
      ],
    },
    {
      name: 'publishers',
      type: 'array',
      label: 'Publisher(s)',
      fields: [
        { name: 'name', type: 'text', label: 'Name' },
        { name: 'split', type: 'number', label: 'Split %', min: 0, max: 100 },
      ],
    },
    {
      name: 'soundRecordingOwners',
      type: 'array',
      label: 'Sound Recording Copyright Owner(s)',
      fields: [
        { name: 'name', type: 'text', label: 'Name' },
        { name: 'split', type: 'number', label: 'Split %', min: 0, max: 100 },
      ],
    },
    { name: 'promoLink', type: 'text', label: 'Preferred Promo Link' },
    { name: 'bandcamp', type: 'text', label: 'Bandcamp' },
    { name: 'instagram', type: 'text', label: 'Instagram' },
    { name: 'website', type: 'text', label: 'Website' },
    { name: 'firstName', type: 'text', label: 'First Name', required: true },
    { name: 'lastName', type: 'text', label: 'Last Name', required: true },
    {
      name: 'affiliation',
      type: 'select',
      label: 'Affiliation',
      required: true,
      options: [
        { label: 'Songwriter', value: 'songwriter' },
        { label: 'Band Member', value: 'band_member' },
        { label: "Artist's Manager", value: 'manager' },
        { label: 'Label Representative', value: 'label_rep' },
        { label: 'Other', value: 'other' },
      ],
    },
    { name: 'email', type: 'email', label: 'Email', required: true },
    { name: 'phone', type: 'text', label: 'Phone', required: true },
    { name: 'trackUrl', type: 'text', label: 'Track URL', admin: { readOnly: true } },
    { name: 'bandPhotoUrl', type: 'text', label: 'Band Photo URL', admin: { readOnly: true } },
    { name: 'trackFilename', type: 'text', label: 'Track Filename', admin: { readOnly: true } },
    { name: 'betterAuthId', type: 'text', label: 'Better Auth User ID', admin: { readOnly: true } },
    { name: 'agreementAccepted', type: 'checkbox', label: 'Agreement Accepted' },
    {
      name: 'agreementTimestamp',
      type: 'text',
      label: 'Agreement Timestamp',
      admin: { readOnly: true },
    },
    { name: 'agreementIp', type: 'text', label: 'Agreement IP', admin: { readOnly: true } },
    {
      name: 'agreementVersion',
      type: 'text',
      label: 'Agreement Version',
      defaultValue: '2026-v1',
      admin: { readOnly: true },
    },
    {
      name: 'status',
      type: 'select',
      label: 'Status',
      defaultValue: 'pending',
      options: [
        { label: 'Pending', value: 'pending' },
        { label: 'Under Review', value: 'under_review' },
        { label: 'Selected', value: 'selected' },
        { label: 'Not Selected', value: 'not_selected' },
      ],
    },
  ],
  timestamps: true,
}
